[package]
name = "ffi"
version = "0.1.0"
authors = ["The es-pack-js Developers", "The wasm-bindgen Developers"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2"
