import 'regenerator-runtime/runtime.js';
import { decode } from 'base64-arraybuffer';
import { pkgJs, pkgWasm } from '__pkg.esm.js';

export default class Inflater {
    static async new() {
        // TODO !!!! polyfill `TextDecoder` stuff for Node.js
        const initJs = new TextDecoder().decode(this.getPkgJs());

        // Create the 'pure' version of the wasm_bindgen's `init()`
        const init = (new Function(`return () => { ${initJs} return wasm_bindgen; };`))
            .call(null);

        const wbg = init();

        // According to 'pkg/<name>.js' generated by
        // `wasm-pack --build --target no-modules`, calling `wbg(input)`
        // is such that the type of `input` can be one of:
        // 'string', `Request`, or `URL`. `input` is `fetch()`-ed internally.

        // TODO no `URL.createObjectURL()` in Node.js; do sth about it later.
        const url = URL.createObjectURL(
            new Blob([this.getPkgWasm()], {type: 'application/wasm'}));
        const wasm = await wbg(url);
        URL.revokeObjectURL(url);

        return { wbg, wasm };
    }

    // Return `ArrayBuffer` representation of bundled wasm-pack pkg files
    static getPkgJs() { return decode(pkgJs); }
    static getPkgWasm() { return decode(pkgWasm); }
};
