# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    #branches: [ master ]
    branches: [ debug-puppeteer ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x, 22.x]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - if: contains(matrix.os, 'windows')
      name: windows - Set bash
      run: npm config set script-shell bash
    #- run: npm ci
    - run: npm i
    - run: npm run build --if-present
    - if: contains(matrix.os, 'ubuntu')
      name: ubuntu - Install Rust
      run: |
        curl -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
        rustup toolchain install stable
        rustup target add wasm32-unknown-unknown --toolchain stable
        rustup default stable
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - if: contains(matrix.os, 'windows')
      name: windows - Run tests
      run: npm run test:windows
      env:
        CI: true
    - if: contains(matrix.os, 'ubuntu')
      name: ubuntu - Run tests
      run: npm test
      env:
        CI: true
